default_settings: null
behaviors:
  Generator:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0008
      beta: 0.0001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 10000
    max_steps: 50000
    time_horizon: 64
    summary_freq: 1000
    threaded: false
    self_play: null
    behavioral_cloning: null
  Solver:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.0003
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 10000
    max_steps: 500000
    time_horizon: 64
    summary_freq: 1000
    threaded: true
    self_play: null
    behavioral_cloning: null
env_settings:
  env_path: /home/bears_bears/Unity_projects/Flappy_bird/Builds/Linux_server/3_curriculum/Flappy_bird_RL_curriculum_3.x86_64
  env_args: null
  base_port: 5005
  num_envs: 50
  num_areas: 1
  seed: -1
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20.0
  target_frame_rate: -1
  capture_frame_rate: 30
  no_graphics: true
environment_parameters:
  aux_input:
    curriculum:
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 3309
          value: 1
      name: Easy
      completion_criteria:
        behavior: Solver
        measure: reward
        min_lesson_length: 50
        signal_smoothing: true
        threshold: 1.0
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 3310
          value: 0.5
      name: Moderate_Easy
      completion_criteria:
        behavior: Solver
        measure: progress
        min_lesson_length: 0
        signal_smoothing: true
        threshold: 0.4
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 3311
          value: 0
      name: Moderate
      completion_criteria:
        behavior: Solver
        measure: progress
        min_lesson_length: 0
        signal_smoothing: true
        threshold: 0.55
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 3312
          value: -0.5
      name: Moderate_Hard
      completion_criteria:
        behavior: Solver
        measure: progress
        min_lesson_length: 0
        signal_smoothing: true
        threshold: 0.7
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 3313
          value: -1
      name: Hard
      completion_criteria: null
checkpoint_settings:
  run_id: curriculum2
  initialize_from: null
  load_model: false
  resume: false
  force: true
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: null
debug: false
