default_settings: null
behaviors:
  Generator:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 4096
      learning_rate: 0.001
      beta: 0.0007
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
      curiosity:
        gamma: 0.99
        strength: 0.03
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
        learning_rate: 0.001
        encoding_size: null
    init_path: results\Curr36gEasy\Generator\checkpoint.pt
    keep_checkpoints: 5
    checkpoint_interval: 1000
    max_steps: 30000
    time_horizon: 64
    summary_freq: 250
    threaded: false
    self_play: null
    behavioral_cloning: null
  Solver:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 2048
      learning_rate: 0.002
      beta: 0.001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
    init_path: results\Curr36gEasy\Solver\checkpoint.pt
    keep_checkpoints: 20
    checkpoint_interval: 10000
    max_steps: 300000
    time_horizon: 64
    summary_freq: 1000
    threaded: true
    self_play: null
    behavioral_cloning: null
env_settings:
  env_path: Z:\Git\Flappy_bird\Builds\Windows\Curr36\Flappy_bird.exe
  env_args: null
  base_port: 5000
  num_envs: 20
  num_areas: 1
  seed: -1
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 3.0
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true
environment_parameters:
  n_obstacles:
    curriculum:
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 6211
          value: 20
      name: Lesson1
      completion_criteria: null
  aux_input:
    curriculum:
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 6212
          value: -1
      name: Lesson1
      completion_criteria: null
checkpoint_settings:
  run_id: Curr36gHard
  initialize_from: Curr36gEasy
  load_model: false
  resume: false
  force: false
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: cuda
debug: false
