default_settings: null
behaviors:
  Generator:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.0005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 1000
    max_steps: 150000
    time_horizon: 64
    summary_freq: 250
    threaded: false
    self_play: null
    behavioral_cloning: null
  Solver:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.0003
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
    init_path: null
    keep_checkpoints: 5
    checkpoint_interval: 10000
    max_steps: 1500000
    time_horizon: 64
    summary_freq: 1000
    threaded: true
    self_play: null
    behavioral_cloning: null
env_settings:
  env_path: Z:\Git\Flappy_bird\Builds\Windows\Curr21\Flappy_bird.exe
  env_args: null
  base_port: 5005
  num_envs: 20
  num_areas: 1
  seed: -1
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 7.0
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true
environment_parameters:
  n_obstacles:
    curriculum:
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 5243
          value: 4
      name: Lesson1
      completion_criteria:
        behavior: Solver
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.2
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 5244
          value: 6
      name: Lesson2
      completion_criteria:
        behavior: Solver
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.4
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 5245
          value: 10
      name: Lesson3
      completion_criteria:
        behavior: Solver
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.5
        require_reset: false
    - value:
        sampler_type: constant
        sampler_parameters:
          seed: 5246
          value: 25
      name: Lesson4
      completion_criteria:
        behavior: Solver
        measure: reward
        min_lesson_length: 100
        signal_smoothing: true
        threshold: 0.5
        require_reset: false
  aux_input:
    curriculum:
    - value:
        sampler_type: multirangeuniform
        sampler_parameters:
          seed: 5247
          intervals:
          - - -1.0
            - -1.0
          - - -1.0
            - -1.0
          - - 1.0
            - 1.0
          - - 1.0
            - 1.0
      name: Lesson3
      completion_criteria: null
checkpoint_settings:
  run_id: Curr21
  initialize_from: null
  load_model: false
  resume: false
  force: false
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: cuda
debug: false
