behaviors:
  Generator:
    trainer_type: ppo
  
    max_steps: 5e5
    time_horizon: 64
    summary_freq: 1000
    checkpoint_interval: 50000

    hyperparameters:
      batch_size: 128
      beta: 0.005
      buffer_size: 2048
      epsilon: 0.2
      lambd: 0.95
      learning_rate: 0.0003
      learning_rate_schedule: linear
      num_epoch: 3    


    network_settings:
      vis_encode_type: simple
      num_layers: 2
      normalize: false
      hidden_units: 64
      memory: null



    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
