behaviors:
  Generator:
    trainer_type: ppo
  
    max_steps: 2.5e5
    time_horizon: 64
    summary_freq: 250
    checkpoint_interval: 1000

    hyperparameters:
      batch_size: 2048
      beta: 0.003
      buffer_size: 4096
      epsilon: 0.2
      lambd: 0.95
      learning_rate: 0.001
      learning_rate_schedule: linear
      num_epoch: 3    


    network_settings:
      vis_encode_type: simple
      num_layers: 2
      normalize: true
      hidden_units: 128
      memory: null

    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      curiosity:
        strength: 0.001
        gamma: .99
        learning_rate: .001
        
  Solver:
    trainer_type: ppo
  
    max_steps: 3e6
    time_horizon: 64
    summary_freq: 1000
    checkpoint_interval: 10000
    keep_checkpoints: 20
    
    hyperparameters:
      batch_size: 32
      beta: 0.001
      buffer_size: 2048
      epsilon: 0.2
      lambd: 0.95
      learning_rate: 0.002
      learning_rate_schedule: linear
      num_epoch: 3    


    network_settings:
      vis_encode_type: simple
      num_layers: 2
      normalize: false
      hidden_units: 512
      memory: null


    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      curiosity:
        strength: 0.001
        gamma: .99
        learning_rate: .001
    threaded: true
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 2
  target_frame_rate: -1
  capture_frame_rate: 60
  
environment_parameters:
  n_obstacles:
    curriculum:
      - name: Lesson1 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Solver
          threshold: .45
          signal_smoothing: false
          min_lesson_length: 10
        value: 0
      - name: Lesson2 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Solver
          threshold: .5
          min_lesson_length: 10
        value: 10
#      - name: Lesson3 # The '-' is important as this is a list
#        completion_criteria:
#          measure: reward
#          behavior: Solver
#          threshold: .6
#          min_lesson_length: 100
#        value: 100
#      - name: Lesson4 # The '-' is important as this is a list
#        completion_criteria:
#          measure: reward
#          behavior: Solver
#          threshold: 1.4
#          min_lesson_length: 100
#        value: 11

  aux_input:
    curriculum:
      - name: Lesson1 # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: Solver
          threshold: .6
          min_lesson_length: 100
        value: 1
      - name: Lesson4 # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: Solver
          threshold: .7
        value: -1
#     - name: Lesson3
#       value:
#         sampler_type: multirangeuniform
#         sampler_parameters:
#           intervals: [[0,0], [.5, .5], [-.5, -.5]]

