behaviors:
  Generator:
    trainer_type: ppo
  
    max_steps: 3.5e5
    time_horizon: 64
    summary_freq: 1000
    checkpoint_interval: 1000

    hyperparameters:
      batch_size: 2048
      beta: 0.003
      buffer_size: 4096
      epsilon: 0.2
      lambd: 0.95
      learning_rate: 0.001
      learning_rate_schedule: linear
      num_epoch: 3    


    network_settings:
      vis_encode_type: simple
      num_layers: 2
      normalize: true
      hidden_units: 512
      memory: null

    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      curiosity:
        strength: 0.003
        gamma: .99
        learning_rate: .001
        
  Solver:
    trainer_type: ppo
  
    max_steps: 3.5e6
    time_horizon: 64
    summary_freq: 1000
    checkpoint_interval: 10000
    keep_checkpoints: 5
    
    hyperparameters:
      batch_size: 64
      beta: 0.002
      buffer_size: 2048
      epsilon: 0.2
      lambd: 0.95
      learning_rate: 0.002
      learning_rate_schedule: linear
      num_epoch: 3    


    network_settings:
      vis_encode_type: simple
      num_layers: 2
      normalize: true
      hidden_units: 512
      memory: null


    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
#      curiosity:
#        strength: 0.000001
#        gamma: .85
#        learning_rate: .001
    threaded: true
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 1
  target_frame_rate: -1
  capture_frame_rate: 60
  
environment_parameters:
  n_obstacles:
    curriculum:
      - name: Lesson1 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: Solver
          threshold: .01
          signal_smoothing: false
          min_lesson_length: 50
        value: 10
#      - name: Lesson2 # The '-' is important as this is a list
#        completion_criteria:
#          measure: reward
#          behavior: Solver
#          threshold: .2
#          min_lesson_length: 70
#        value: 3
#      - name: Lesson3 # The '-' is important as this is a list
#        completion_criteria:
#          measure: reward
#          behavior: Solver
#          threshold: .25
#          min_lesson_length: 100
#        value: 6
#      - name: Lesson2 # The '-' is important as this is a list
#        completion_criteria:
#          measure: reward
#          behavior: Solver
#          threshold: .5
#          min_lesson_length: 10
#        value: 10
#      - name: Lesson3 # The '-' is important as this is a list
#        completion_criteria:
#          measure: reward
#          behavior: Solver
#          threshold: .6
#          min_lesson_length: 100
#        value: 100
#      - name: Lesson4 # The '-' is important as this is a list
#        completion_criteria:
#          measure: reward
#          behavior: Solver
#          threshold: 1.4
#          min_lesson_length: 100
#        value: 11

  aux_input:
    curriculum:
      - name: Lesson1 # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: Solver
          threshold: .3
          min_lesson_length: 100
        value: 1
      - name: Lesson2 # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: Solver
          threshold: .5
        value: -1
      - name: Lesson3 # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: Solver
          threshold: .75
          min_lesson_length: 100
        value: 1
      - name: Lesson4 # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: Solver
          threshold: .95
        value: -1
      - name: Lesson3
        value:
          sampler_type: multirangeuniform
          sampler_parameters:
            intervals: [[0,0], [.5, .5], [-.5, -.5]]

