behaviors:
  Generator:
    trainer_type: ppo
  
    max_steps: 1e5
    time_horizon: 64
    summary_freq: 10
    checkpoint_interval: 1000

    hyperparameters:
      batch_size: 128
      beta: 0.0003
      buffer_size: 2048
      epsilon: 0.2
      lambd: 0.95
      learning_rate: 0.0003
      learning_rate_schedule: linear
      num_epoch: 3    


    network_settings:
      vis_encode_type: simple
      num_layers: 3
      normalize: false
      hidden_units: 256
      memory: null

    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
        
  Solver:
    trainer_type: ppo
  
    max_steps: 1e6
    time_horizon: 64
    summary_freq: 40
    checkpoint_interval: 10000

    hyperparameters:
      batch_size: 128
      beta: 0.0003
      buffer_size: 2048
      epsilon: 0.2
      lambd: 0.95
      learning_rate: 0.0003
      learning_rate_schedule: linear
      num_epoch: 3    


    network_settings:
      vis_encode_type: simple
      num_layers: 2
      normalize: false
      hidden_units: 256
      memory: null


    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
    threaded: true
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 7
  target_frame_rate: -1
  capture_frame_rate: 60
  
environment_parameters:
  n_obstacles:
    curriculum:
      - name: Lesson1 # The '-' is important as this is a list
        value: 10
  aux_input:
    curriculum:
      - name: Lesson1 # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: Solver
          threshold: .2
        value: -1
      - name: Lesson2 # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: Solver
          threshold: .4
        value: 1
      - name: Lesson3 # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: Solver
          threshold: .55
        value: -0.5
      - name: Lesson4 # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: Solver
          threshold: .7
        value: 0.5
      - name: Lesson5 # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: Solver
          threshold: .85
        value: -2
      - name: Lesson6 # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: Solver
          threshold: .55
        value: 2

