behaviors:       
  Solver:
    trainer_type: ppo
  
    max_steps: 3e6
    time_horizon: 64
    summary_freq: 1000
    checkpoint_interval: 10000
    keep_checkpoints: 20
    
    hyperparameters:
      batch_size: 64
      beta: 0.002
      buffer_size: 2048
      epsilon: 0.2
      lambd: 0.95
      learning_rate: 0.002
      learning_rate_schedule: linear
      num_epoch: 3    


    network_settings:
      vis_encode_type: simple
      num_layers: 2
      normalize: true
      hidden_units: 512
      memory: null


    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
    threaded: true
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 1
  target_frame_rate: -1
  capture_frame_rate: 60
  
environment_parameters:
#  heur_hdist_min:
#      sampler_type: multirangeuniform
#      sampler_parameters:
#        intervals: [[2, 4]]
#  heur_hdist_max: 
#      sampler_type: multirangeuniform
#      sampler_parameters:
#        intervals: [[2, 4]]
#  heur_height_min: 
#      sampler_type: multirangeuniform
#      sampler_parameters:
#        intervals: [[2, 5]]
#  heur_height_max: 
#      sampler_type: multirangeuniform
#      sampler_parameters:
#        intervals: [[2, 5]]
 
#     - name: Lesson3
#        value:
#         sampler_type: multirangeuniform
#         sampler_parameters:
#           intervals: [[0,0], [.5, .5], [-.5, -.5]]

