behaviors:
  FlappyBird:
    trainer_type: ppo
  
    max_steps: 8e5
    time_horizon: 64
    summary_freq: 1000
    checkpoint_interval: 50000

    hyperparameters:
      batch_size: 128
      beta: 0.0005
      buffer_size: 2048
      epsilon: 0.2
      lambd: 0.95
      learning_rate: 0.0003
      learning_rate_schedule: linear
      num_epoch: 3    


    network_settings:
      vis_encode_type: simple
      num_layers: 2
      normalize: false
      hidden_units: 128
      memory: null



    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 1
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false        
